### ISSUE TITLE
After upgrading from QAF 2.1.14-RC1 to 2.1.15, BDD steps are breaking

### ISSUE THREAD

**Issue by raviguptasmarsh** [qmetry/qaf#325]
Multiple variables in the value of a single key cannot be used directly in the BDD file.

### QAF Version
> Upgraded from QAF 2.1.14-RC1 to 2.1.15

### Steps To Reproduce
    1.Create a bdd file with this step:

Given '${client.status.active.new}' client id available as 'clientId'

In the property file add the property:

Case 1: 
client.status.active.new = ${target.env1}active => This passes the value fine from bdd step to method.

Case 2:
client.status.active.new = active${target.env2} => This passes the value fine from bdd step to method.

Case 3:
**client.status.active.new = ${target.env1}active${target.env2} => This passes null to the java method and is breaking most of our test cases as we had been using more than one ${variable} for a single property in our properti files**

This was working fine in QAF 2.1.14-RC1

### Is the issue reproducible on runner?
- [ ] Maven
- [ ] Eclipse

**Comment by cjayswal** [comment]
It looks something wrong with your configuration. If not, will you please provide testcase/code to reproduce the behavior. I tired below and found working fine with latest qaf:

```
public static void main(String[] args) {
	ConfigurationManager.getBundle().setProperty("step.provider.pkg", "com.qmetry.qaf.example");

	ConfigurationManager.getBundle().setProperty("target.env1", "env1");
	ConfigurationManager.getBundle().setProperty("target.env2", "env2");
	ConfigurationManager.getBundle().setProperty("client.status.active.new", "${target.env1}active${target.env2}");
		System.out.println(ConfigurationManager.getBundle().getString("client.status.active.new"));
	StringTestStep.execute("'${client.status.active.new}' client id available as 'clientId'");
}
	
@QAFTestStep(description="{s} client id available as {s1}")
public static void step1(String s, String s1){
	System.out.printf("\ns: %s s1:%s\n", s, s1);
}
```
Output:

> env1activeenv2
>s: env1activeenv2 s1:clientId

**Comment by raviguptasmarsh** [comment]
@cjayswal Surprisingly, the same code that you provided does not work for me and prints:
s: null s1:clientId


This is the QAF dependency we are using in our project. Can you please verify it?

<dependency>
			<groupId>com.qmetry</groupId>
			<artifactId>qaf</artifactId>
			<version>2.1.15</version>
		</dependency>
		<dependency>
			<groupId>com.qmetry</groupId>
			<artifactId>qaf-support-ws</artifactId>
			<version>2.1.15</version>
			<exclusions>
				<exclusion>
					<groupId>ch.qos.logback</groupId>
					<artifactId>logback-classic</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>com.qmetry</groupId>
			<artifactId>qaf-support</artifactId>
			<version>2.1.15</version>
		</dependency>
		<dependency>
			<groupId>org.jdom</groupId>
			<artifactId>jdom</artifactId>
			<version>2.0.0</version>
               </dependency>

**Comment by raviguptasmarsh** [comment]
But same thing works with 3.0.0-RC3 version.
However with this version, 3.0.0-RC3, we are facing another issue:

java.lang.NoSuchMethodError: com.qmetry.qaf.automation.step.client.TestNGScenario.getClassOrFileName()Ljava/lang/String;
	at com.qmetry.qaf.automation.testng.report.ReporterUtil.getTestClassName(ReporterUtil.java:428)
	at com.qmetry.qaf.automation.testng.report.ReporterUtil.getClassDir(ReporterUtil.java:423)
	at com.qmetry.qaf.automation.testng.report.ReporterUtil.createMethodResult(ReporterUtil.java:259)
	at com.qmetry.qaf.automation.testng.pro.QAFTestNGListener2.report(QAFTestNGListener2.java:181)
	at com.qmetry.qaf.automation.testng.pro.QAFTestNGListener.onTestSuccess(QAFTestNGListener.java:121)

**Comment by raviguptasmarsh** [comment]
In the ReporterUtil at line 427 :
String classOrFile = ((TestNGScenario)result.getMethod()).getClassOrFileName();

Do I need to implement this method in my class:
class TestNGScenario extends TestNGMethod {

}


What will be its implementation ? What should it return ?

**Comment by raviguptasmarsh** [comment]
Could not really understand the rationale behind this method:

private static String getTestClassName(ITestResult result){
		if((result.getMethod() instanceof TestNGScenario)){
			String classOrFile = ((TestNGScenario)result.getMethod()).getClassOrFileName();
			File f = new File(classOrFile);
			if(f.exists() && !classOrFile.equalsIgnoreCase(result.getTestClass().getName())) {
				return FilenameUtils.removeExtension(f.getName());
			}
			return classOrFile;
		}
		return result.getTestClass().getName();
	}

**Comment by cjayswal** [comment]
is this duplicate of #315?
